theme = "ao"

[editor]
line-number = "relative"
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 40

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"

[editor.lsp]
display-inlay-hints = true
