#theme = rose_pine_moon

[editor]
bufferline = "always"
continue-comments = false
color-modes = true
line-number = "relative"
popup-border = "all"
rulers = [80]
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 0

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true
max-wrap = 40

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [ "mode", "position", "position-percentage", "spinner"]
center = [ "read-only-indicator", "file-base-name"]
right = [ "diagnostics", "file-modification-indicator", "file-type","spinner", "version-control" ]
separator = "|"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"d" = "delete_selection_noyank"
A-x = "delete_selection"

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"
l = ":toggle lsp.display-inlay-hints"
m = ":toggle indent-guides.render"


